export const clinic = {
  name: "PLACEHOLDER — Este contenido se reemplaza automáticamente",
  logo: null as string | null,
  tagline: "Sitio web en construcción",
  description: "Este es un template placeholder. El contenido real se genera automáticamente durante el pipeline de creación.",
  colors: {
    primary: "#6366f1",
    secondary: "#1e1b4b",
    accent: "#818cf8",
    neutral: "#f5f3ff",
  },
  phone: "",
  whatsapp: "",
  whatsappMessage: "",
  email: "",
  address: {
    street: "",
    city: "",
    province: "",
    postalCode: "",
    country: "España",
  },
  googleMapsUrl: "",
  googleMapsEmbed: "",
  coordinates: { lat: 40.4168, lng: -3.7038 },
  schedule: [
    { days: "Lunes - Viernes", hours: "09:00 - 20:00" },
    { days: "Sábado", hours: "Cerrado" },
    { days: "Domingo", hours: "Cerrado" },
  ],
  social: {
    instagram: null as string | null,
    facebook: null as string | null,
    linkedin: null as string | null,
    tiktok: null as string | null,
  },
  reviews: {
    rating: 0,
    count: 0,
    url: "#",
    featured: [] as Array<{ author: string; rating: number; text: string; date: string }>,
  },
  services: [
    {
      id: "placeholder",
      name: "Servicio de ejemplo",
      description: "Este contenido se genera automáticamente.",
      benefits: ["Beneficio 1", "Beneficio 2"],
      icon: "Star",
    },
  ],
  process: [
    { step: 1, title: "Contacta", description: "Solicita información" },
    { step: 2, title: "Consulta", description: "Evaluamos tus necesidades" },
    { step: 3, title: "Servicio", description: "Realizamos el trabajo" },
    { step: 4, title: "Resultado", description: "Disfruta del resultado" },
  ],
  whyUs: [
    {
      title: "Profesionalidad",
      description: "Años de experiencia avalan nuestro trabajo",
      icon: "Award",
    },
  ],
  team: [
    {
      name: "Equipo profesional",
      role: "Especialistas",
      image: "/images/team/placeholder.jpg",
      bio: "Profesionales comprometidos con la calidad.",
    },
  ],
  gallery: [] as Array<{ src: string; alt: string }>,
  faq: [
    {
      question: "¿Cómo puedo contactar?",
      answer: "Puede contactarnos por teléfono o WhatsApp.",
    },
  ],
  seo: {
    titleTemplate: "%s | Sitio en construcción",
    defaultTitle: "Sitio web en construcción",
    defaultDescription: "Sitio web en construcción. Contenido generado automáticamente.",
    keywords: [] as string[],
    ogImage: "/og-image.jpg",
  },
  legal: {
    companyName: "PLACEHOLDER",
    cif: "",
    registeredAddress: "",
  },
  heroHeadline: ["Sitio web", "en", "construcción"],
  heroDescription: "Este contenido se reemplaza automáticamente durante la generación.",
  specialty: "",
  ctaLabel: "Contactar",
  ctaHeadline: "¿Necesitas más información?",
  ctaDescription: "Contacta con nosotros para más información.",
  statsLabel: "Clientes",
  schemaType: "LocalBusiness",
  sectionCopy: {
    servicesLabel: "Servicios",
    servicesTitle: "Nuestros servicios",
    servicesDescription: "Servicios profesionales adaptados a tus necesidades.",
    processLabel: "Proceso",
    processTitle: "Cómo trabajamos",
    processDescription: "Un proceso simple y transparente.",
    whyUsLabel: "Por Qué Elegirnos",
    whyUsTitle: "Profesionalidad y confianza",
    whyUsDescription: "Comprometidos con la calidad y la satisfacción.",
    reviewsLabel: "Opiniones",
    reviewsTitle: "Lo que dicen nuestros clientes",
    galleryLabel: "Galería",
    galleryTitle: "Nuestras instalaciones",
    galleryDescription: "Conoce nuestro espacio de trabajo",
    faqLabel: "FAQ",
    faqTitle: "Preguntas frecuentes",
    faqDescription: "Resolvemos las dudas más comunes.",
    locationLabel: "Ubicación",
    locationTitle: "Cómo llegar",
    teamLabel: "Equipo",
    teamTitle: "Nuestro equipo",
    teamDescription: "Profesionales a tu servicio",
  },
}

export type Clinic = typeof clinic
